### ISSUE TITLE
Design Documentation?

### ISSUE THREAD

**Issue by seandenigris** [ba-st/Willow#124]
The individual Playground  examples are really nice and easy to adapt, but I'm unclear on the overall design. For instance, the examples seem to override the session and application context. How would I know if this is necessary or appropriate for my app? Another example, `WPLiveDocumentation` overrides `#initialRequest:`. The method comment in `WAPresenter>>#initialRequest:` says "When a new session is started, all visible presenters (components or tasks) receive this message with the request as argument. A common usage for this is to initialize their state depending on the URL of the request." However, WPLiveDocumentation throws away the argument. It's unclear what the pattern is here…

**Comment by mtabacman** [comment]
initialRequest is a Seaside message that allows interacting with the HTTP request once it's made available to the application. When you need to interact with the application session, the code must be written here instead of in the initialization method for the application. This should be covered in the future in a [Medium post](https://medium.com/mercap-tech-blog/willow-introduction-d498e198dd4a).
You won't always need to interact with the argument, still the code must be written at this point to ensure the existence of the objects you'll be interacting with.

**Comment by seandenigris** [comment]
> initialRequest is a Seaside message that allows… When you need to interact with the application session

Got it! Thanks :) Should I ask more questions here as they come up or is Slack a better place?
