### ISSUE TITLE
Willow in VW; Communication with the writers of Willow

### ISSUE THREAD

**Issue by Shaping** [ba-st/Willow#154]
Hi Gabriel.

I have everything loaded into Pharo 8.  Thanks.

I'm working through the tutorial now.

Will the latest version of Seaside and Willow be available soon for VW?

How can I communicate with you via e-mail?  The response you sent me was from a no-reply address.   Should I post to pharo-dev or pharo-users instead?

Shaping

**Comment by gcotelli** [comment]
Hi, Shaping you can contact us by mail (if you have the presentation working the last slide has the contact information). We also have a channel in the Pharo discord server and in the ba-st Slack (if you want an invitation just let me know). Posting to pharo-users or pharo-dev is totally Ok also and usually is better because that way the info keeps useful for future users. I will reply with some more information on the other issue.
